### ISSUE TITLE
Any plans to finalize the port?

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/leaflet#10]
Dear maintainers,

first of all: many thanks for porting this module to Backdrop!

It seems to me, that the work on this has stalled, though. Are there any plans to continue?
I'm not sure, how much effort it will be, but I'm willing to help.

**Comment by indigoxela** [comment]
@earthday47 it seems, you're listed as maintainer for Leaflet. Are there any plans to continue work?

Or, if your spare time does not allow that, are you interested in a co-maintainer?

**Comment by earthday47** [comment]
Hi @indigoxela, thanks for your willingness to contribute! Unfortunately yeah, I haven't been active with Backdrop for some time, so if you're willing to help keep the project going, I'm more than happy to make you co-maintainer!

**Comment by indigoxela** [comment]
@earthday47 cool, many thanks. I think, the official way of doing that is to merge a pull request with the new co-maintainer listed in the readme - this PR has been created. :smiley:

**Comment by earthday47** [comment]
@indigoxela have you applied to be a Backdrop contributor yet? https://backdropcms.org/contribute/join

**Comment by indigoxela** [comment]
> have you applied to be a Backdrop contributor yet?

Obviously you haven't been active in the Backdrop community for a while. :rofl: I'm already maintainer of several modules, yes.
Or course, I'm already [member](https://github.com/indigoxela) of the core and contrib organizations.

Oh, I just realized that my memberships weren't published on Github - done that now.

**Comment by earthday47** [comment]
Haha yeah... thanks so much for working on this. Done!
