### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/leaflet#13]
Hi,
are there any plans to port the other leaflet modules from D7? E.g.

https://www.drupal.org/project/leaflet_markercluster
https://www.drupal.org/project/leaflet_label
https://www.drupal.org/project/leaflet_views_ajax_popup
https://www.drupal.org/project/leaflet_ajax_features

**Comment by djzwerg** [comment]
Maybe it would make sense to have the [IP Geolocation Views & Maps module](https://github.com/backdrop-contrib/ip_geoloc) fully ported?

**Comment by indigoxela** [comment]
Module leaflet_markercluster is already included in Backdrop's leaflet module (see modules subdirectory).
As well as leaflet_more_maps.

I don't know about the other ones.

**Comment by indigoxela** [comment]
> Maybe it would make sense to have the IP Geolocation Views & Maps module fully ported?

Sure, but that's a different issue queue. :wink:

The maintainer explicitly asks for testing and will surely appreciate it.
