### ISSUE TITLE
Safari on macOS popup problem since library update to 1.7.1

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/leaflet#17]
This has been reported in the Zulip chat:

> I no longer get the popup tooltips when clicking on an icon.
> Looks like it is specific to Safari on MacOS (Big Sur).

This Leaflet issue (and all those "closed duplicate") seem related: https://github.com/Leaflet/Leaflet/issues/7255

**Comment by indigoxela** [comment]
There seems to be a workaround: https://github.com/domoritz/leaflet-locatecontrol/issues/280#issuecomment-773970457

But I can't test it. Any volunteers?

**Comment by indigoxela** [comment]
If you're using markercluster, put this into your modules/leaflet_markercluster/js/leaflet_markercluster.backdrop.js

```
        settings.tap = false;
        // instantiate our new map
```
in line 29 (the comment is only there for better orientation). Does this help?

**Comment by tkcent** [comment]
Yup, that works!

Weirdly enough, I can actually get the tooltip to work ONE time without the fix.  If I right click on the page, click Inspect Element, and then choose the Console tab, I can now click on ONE icon and get the tooltip.  Subsequent clicks on any icon do not work.  This doesn't work if I open the console directly from the Develop menu at the top or use the Command-Option-C shortcut.

**Comment by indigoxela** [comment]
Just to make sure: turning "tap" off completely fixes it for you in Safari? Subsequent clicks also work as expected?

**Comment by indigoxela** [comment]
The change has been committed.

FTR - this setting is a workaround thing on its own (description from official docs):

> **tap**
> 
> Enables mobile hacks for supporting instant taps (fixing 200ms click delay on iOS/Android) and touch holds (fired as contextmenu events).

There *could* be side effects on iOS or Android, so this needs a little more testing.

**Comment by indigoxela** [comment]
Seems like no severe side effects appeared. Time to close this issue.
