### ISSUE TITLE
Z-index higher than admin menu causing some objects to sit above menu

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/leaflet#24]
I have a google map displaying and the zoom control is displaying on top of the Admin Menu.

This is because the CSS z-index value is set to 1000. The admin menu z-index value is 999.

The offending CSS is this as part of leaflet.css:

`.leaflet-top,
.leaflet-bottom {
	position: absolute;
	z-index: 1000;
	pointer-events: none;
	}`

You could easily argue that the z-index value for the Admin Menu in core is too low, and it could go as high as necessary, assuming it's the one element you'd want to be the uppermost layer. However it might be easier to adjust the module css for the time being.

**Comment by indigoxela** [comment]
Hi @sbgraphicdesign,

many thanks for taking the time to report.

I'm aware, that Leaflet (the mapping library this module utilizes) has a higher z-index than the admin menu from core.
I'm just not sure if this module can (or should) solve it.

**Comment by indigoxela** [comment]
Here's a pull request for testing: https://github.com/backdrop-contrib/leaflet/pull/25

**Comment by indigoxela** [comment]
A related core issue, which only addresses the admin menu, but not the smart-menu dropdown: https://github.com/backdrop/backdrop-issues/issues/5372

**Comment by indigoxela** [comment]
@sbgraphicdesign what do you think, does the approach of this [PR](https://github.com/backdrop-contrib/leaflet/pull/25) make sense to you? Are you interested in testing?
