### ISSUE TITLE
Different Map Markers based on node type or based on a field 

### ISSUE THREAD

**Issue by delinuxco** [backdrop-contrib/leaflet#66]
I am in the middle of migrating a D7 site to Backdrop, in the original site, it uses IP Geolocation Views & Maps to display a map with about 6 different markers based on a Text List field. In the IPGVM module, one could assign different color markers based on the list. 

On my new test site, I have the map working, and the clustering. and the only thing blocking my migration, is the different marker colors. 

Any ideas on how to do this?

**Comment by indigoxela** [comment]
> the original site, it uses IP Geolocation Views & Maps to display a map with about 6 different markers based on a Text List field. In the IPGVM module, one could assign different color markers based on the list.

Although IP Geolocation Views and Maps has no official release, yet, it's available as dev version here: https://github.com/backdrop-contrib/ip_geoloc

I'm not aware of a way to use different marker colors based on a list inside the same view with Leaflet. Especially not in combination with marker clustering. And I have to admit, I don't know how ip_geoloc does that. And I wouldn't know how to do that without quite an amount of coding with this module here.

**Comment by indigoxela** [comment]
Oh, maybe I misunderstood this "based on the list"?

It is possible to use custom icons based on _field values_.
You'd add an image field to your map node type, then adapt the display for the individual node map (if there is), and also adapt the view's setting for "Point icon":

Here a screenshot from the view's Leaflet Map setting:

![views-leaflet-icon-setting](https://github.com/user-attachments/assets/532f2088-1a57-4ad4-9e00-b81a4cd83580)

Getting the image size and position right, needs a little fiddling, but its possible for nodes with geofield and an image field, and also for the view combining those nodes in one map.

But there aren't any pre-defined color icons in this module, you could pick from. You have to create the icons yourself.

**Comment by laryn** [comment]
I’ve never used this, but your screenshot made me wonder: Could field tokens be used in the marker HTML class?

**Comment by indigoxela** [comment]
> Could field tokens be used in the marker HTML class?

No, there's no token replacement on these.

**Comment by delinuxco** [comment]
I just tried IPGV&M and it installed fine, but does not seem to have the same functionality.  I was hoping to be able to do a clean install of Backdrop and import the data from the old site, there were a few things I wanted to do differently. But it looks like I will just have to try to migrate the site in place. I will create a subdomain, copy it over there and then upgrade and see what happens.

This client's site uses a text field list and then assigns it to different color markers.
![Religious Order](https://github.com/user-attachments/assets/47b6d71c-52b5-4451-a7e9-8ee3e488fc0d)
![Marker Styles](https://github.com/user-attachments/assets/48178c97-1041-4c9d-a6d3-7472aafb2c4c)

**Comment by indigoxela** [comment]
> I just tried IPGV&M and it installed fine, but does not seem to have the same functionality.

So, good news and bad news for you? :wink: (Personally, I never used that module so far, so can't provide any help.)

Maybe start a discussion in the issue queue over there re missing functionality: https://github.com/backdrop-contrib/ip_geoloc/issues

Possibly the maintainers are just waiting for someone to get things rolling. :wink: 

> This client's site uses a text field list and then assigns it to different color markers.

No, that's not something feasible with Leaflet alone (without custom code). Marker assignment works differently in this module.

**Comment by delinuxco** [comment]
Yes, I believe you are correct... I will try the upgrade first and see what happens, just for shits and giggles. Then I will hit up IP_geo from there.  Thank you so much for your time.

John

**Comment by delinuxco** [comment]
I have been able to replicate about 60% of the D7 site, I have create the node that IPGV-M uses to generate the map. I recreated the Views with IPGV-M but I keep getting an error. If I switch to just Leaflet or GeoMap it displays just fine. 
IPGV-M has the built in markercluster setup that this site requires and since I am not a coder, I am stuck at the moment.

When trying to access the view:

```
Error
Unsupported operand types: string * float
``` 

In Recent log I get this:

`TypeError: Unsupported operand types: string * float in ip_geoloc_generator_ip_geoloc_marker_locations_alter() (line 61 of /home/latinnet/beta.latinritemass.net/modules/ip_geoloc-1.x-1.x/ip_geoloc_generator/ip_geoloc_generator.module).`

I opened an issue https://github.com/backdrop-contrib/ip_geoloc/issues/17 But I have not had any response, it doesn't look like there is much activity there.

Anyone have any ideas.

**Comment by indigoxela** [comment]
> I opened an issue https://github.com/backdrop-contrib/ip_geoloc/issues/17 But I have not had any response...

Two days ago. :wink: It might make sense to train your patience with OpenSource project maintainers.

> Anyone have any ideas.

I took a quick look, and do have an idea: config should be numeric, but instead of the value of the PHP constants, you're getting a string it seems.

Expected values are defined as: 
```
define('IP_GEOLOC_GENERATOR_GREENWICH_OBSERVATORY_LAT', 51.4777);
define('IP_GEOLOC_GENERATOR_GREENWICH_OBSERVATORY_LON', -0.0015);
```
But the default *config values* are:
```
    "ip_geoloc_generator_center_lat": "IP_GEOLOC_GENERATOR_GREENWICH_OBSERVATORY_LAT",
    "ip_geoloc_generator_center_lon": "IP_GEOLOC_GENERATOR_GREENWICH_OBSERVATORY_LON",
```
^^ the name of the constants instead of the float.

No idea, where the module has its settings page (which path), but you could open the config json file ( ip_geoloc_generator.settings.json in your active config directory) and replace the string values with the numbers:

```
    "ip_geoloc_generator_center_lat": 51.4777,
    "ip_geoloc_generator_center_lon": -0.0015,
```
Not sure if that fixes it - as I already stated, I never used that module - but it seems worth a try.

And maybe @AlexHoebart-ICPDR is interested in that, too.

**Comment by delinuxco** [comment]
AlexHoebart-ICPDR over at [IPGV&M](https://github.com/backdrop-contrib/ip_geoloc/issues/17) did respond, and he recommended to disable the generator submodule and that worked. 

But I have been able to make Leaflet work, sans the Location differentiator ...

Thank you for your help.
