### ISSUE TITLE
Update Leaflet libraries

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/leaflet#7]
This module uses `0.7.5` and the current version is `1.5.1`. I suspect that large of a jump will cause breakage, but the [download page](https://leafletjs.com/download.html) also lists `0.7.7` as the [legacy version](https://github.com/Leaflet/Leaflet/releases/tag/v0.7.7). Maybe short term we can drop in 0.7.7 and long term determine when/if to do a more major version upgrade?

**Comment by laryn** [comment]
Also, is there a better way to include the other plugins which will indicate which version they are? (e.g. fullscreen)

**Comment by laryn** [comment]
For reference, I'm working on [IP_Geoloc](https://github.com/backdrop-contrib/ip_geoloc) which pulls in [a few Leaflet plugins](https://github.com/backdrop-contrib/ip_geoloc/blob/1.x-1.x/ip_geoloc.module#L82-L125) which would probably make more sense in this module. 

Fullscreen is already in this module but it isn't specified as an easy to use separate library and with details of version, etc., [like this (with syntax adjusted for Backdrop)](https://github.com/backdrop-contrib/ip_geoloc/blob/1.x-1.x/ip_geoloc.module#L82-L102).

**Comment by indigoxela** [comment]
Updating the leaflet library is one of my next steps. We'll see how that works.

**Comment by indigoxela** [comment]
The library is now at version 0.7.7. Testing is welcome.

One trouble, we'll be running in is that the libraries directory contains (undocumented) plugins that either didn't get updated in years (probably aren't compatible with a more recent version), or are completely unidentifiable (not sure where they come from).

Removing those might be one of the "breaking changes" I announced in our chat.

**Comment by indigoxela** [comment]
Huh? Can it really be so easy to update all libraries to their latest stable? I doubt it. :smile:

Here's an [experimental branch](https://github.com/backdrop-contrib/leaflet/archive/refs/heads/update-libraries.zip) to download for further testing.

Note: do not just unpack that file over the old directory, but replace the whole leaflet module with the new code.

The simple things, that I'm usually using still seem to work fine. Testing and feedback is welcome.
