### ISSUE TITLE
Add MiniMap plugin

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/leaflet#8]
@earthday47 Are you open to including the [MiniMap plugin](https://github.com/Norkart/Leaflet-Minimap) in this module as a library that other modules can call?

**Comment by indigoxela** [comment]
@laryn are you still interested in the MiniMap plugin? I never used it so far...

**Comment by laryn** [comment]
Still interested but the project I was testing for fell through so I don't have an immediate need for it (or a quick way to test).

**Comment by indigoxela** [comment]
After such a long time of silence it's probably OK to close this issue as stalled.
