### ISSUE TITLE
Feature request: Use leaflet map as field widget

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/leaflet#9]
It would be very nice to use leaflet for choosing the coordinates instead of copy and paste from an external map.

**Comment by indigoxela** [comment]
Is there a Drupal module for that, we can use as template? Writing from scratch is very likely above my head - my js skills are limited.

**Comment by indigoxela** [comment]
@djzwerg did you mean that one? https://www.drupal.org/project/leaflet_widget

**Comment by hajarimanitra** [comment]
@indigoxela Thanks for the initiative. I was trying to figure out how to implement this in the last few days without success. Unfortunately, my js and backdrop skills are very limited as well. I did not know that there is this leaflet_widget module though. I just had a look at it (I downloaded the tar file, did not fork the project). I tried to install it but it needs quite some work. When I enabled the module in Backdrop, it complained about Library not found :
"Error: Call to undefined function libraries_get_path() in leaflet_widget_requirements() (line 15 of C:\xampp\htdocs\geolocation_test\modules\leaflet_widget\leaflet_widget.install)." It requires two libraries:
[Leaflet.draw]: https://github.com/Leaflet/Leaflet.draw
[Leaflet.widget]: https://tnightingale.github.com/Leaflet.widget
Unfortunately, Backdrop's Libraries module is deprecated so we need to overcome that.

**Comment by hajarimanitra** [comment]
I just forked Drupal's Leaflet_widget module
https://git.drupalcode.org/issue/leaflet_widget-3207077/-/tree/3207077-backdrop-port

**Comment by hajarimanitra** [comment]
Please ignore the previous git link. I could not manage to clone or download it. Instead this is the version I am working on now.
The module can be installed. The widget can be selected BUT once in the Create Content page, there is nothing than the field label. 
https://github.com/hajarimanitra/leaflet_widget
P.S. I am new to GIT so I do not know how to share things it

**Comment by indigoxela** [comment]
@hajarimanitra many thanks for offering help. :rocket: I hope to find the time to look into this soon.

**Comment by djzwerg** [comment]
> @djzwerg did you mean that one? https://www.drupal.org/project/leaflet_widget

@indigoxela to port this would exactly solve my request. Should I open a new port request?

**Comment by indigoxela** [comment]
> Should I open a new port request?

@djzwerg I think that's the right way, yes. It seems that @hajarimanitra is also interested in this port.

**Comment by djzwerg** [comment]
> > Should I open a new port request?
> 
> @djzwerg I think that's the right way, yes. It seems that @hajarimanitra is also interested in this port.

Done here: https://github.com/backdrop-ops/contrib/issues/508.
Thx!
